spring:
  datasource:
    url: jdbc:postgresql://localhost:55321/ImgDb
    username: luo
    password: 666666
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true