spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imgdb
    username: luo
    password: 888888
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true